jest.mock('react-native', () => ({
  AppState: {
    currentState: 'active',
    addEventListener: jest.fn(() => ({
      remove: jest.fn(),
    })),
  },
  Platform: {
    OS: 'ios',
    select: jest.fn((obj: Record<string, unknown>) => obj.ios),
  },
}));

jest.mock('react-native-permissions', () => ({
  check: jest.fn(),
  request: jest.fn(),
  checkMultiple: jest.fn(),
  requestMultiple: jest.fn(),
  checkNotifications: jest.fn(),
  requestNotifications: jest.fn(),
  checkLocationAccuracy: jest.fn(),
  requestLocationAccuracy: jest.fn(),
  PERMISSIONS: {
    IOS: {
      APP_TRACKING_TRANSPARENCY: 'ios.permission.APP_TRACKING_TRANSPARENCY',
      BLUETOOTH: 'ios.permission.BLUETOOTH',
      CALENDARS: 'ios.permission.CALENDARS',
      CALENDARS_WRITE_ONLY: 'ios.permission.CALENDARS_WRITE_ONLY',
      CAMERA: 'ios.permission.CAMERA',
      CONTACTS: 'ios.permission.CONTACTS',
      FACE_ID: 'ios.permission.FACE_ID',
      LOCATION_ALWAYS: 'ios.permission.LOCATION_ALWAYS',
      LOCATION_WHEN_IN_USE: 'ios.permission.LOCATION_WHEN_IN_USE',
      MEDIA_LIBRARY: 'ios.permission.MEDIA_LIBRARY',
      MICROPHONE: 'ios.permission.MICROPHONE',
      MOTION: 'ios.permission.MOTION',
      PHOTO_LIBRARY: 'ios.permission.PHOTO_LIBRARY',
      PHOTO_LIBRARY_ADD_ONLY: 'ios.permission.PHOTO_LIBRARY_ADD_ONLY',
      REMINDERS: 'ios.permission.REMINDERS',
      SIRI: 'ios.permission.SIRI',
      SPEECH_RECOGNITION: 'ios.permission.SPEECH_RECOGNITION',
      STOREKIT: 'ios.permission.STOREKIT',
    },
    ANDROID: {
      ACCESS_BACKGROUND_LOCATION:
        'android.permission.ACCESS_BACKGROUND_LOCATION',
      ACCESS_COARSE_LOCATION: 'android.permission.ACCESS_COARSE_LOCATION',
      ACCESS_FINE_LOCATION: 'android.permission.ACCESS_FINE_LOCATION',
      ACTIVITY_RECOGNITION: 'android.permission.ACTIVITY_RECOGNITION',
      BLUETOOTH_CONNECT: 'android.permission.BLUETOOTH_CONNECT',
      BODY_SENSORS: 'android.permission.BODY_SENSORS',
      CALL_PHONE: 'android.permission.CALL_PHONE',
      CAMERA: 'android.permission.CAMERA',
      POST_NOTIFICATIONS: 'android.permission.POST_NOTIFICATIONS',
      READ_CALENDAR: 'android.permission.READ_CALENDAR',
      READ_CONTACTS: 'android.permission.READ_CONTACTS',
      READ_MEDIA_IMAGES: 'android.permission.READ_MEDIA_IMAGES',
      READ_SMS: 'android.permission.READ_SMS',
      RECORD_AUDIO: 'android.permission.RECORD_AUDIO',
      SEND_SMS: 'android.permission.SEND_SMS',
      WRITE_CALENDAR: 'android.permission.WRITE_CALENDAR',
      WRITE_CONTACTS: 'android.permission.WRITE_CONTACTS',
      WRITE_EXTERNAL_STORAGE: 'android.permission.WRITE_EXTERNAL_STORAGE',
    },
  },
  RESULTS: {
    UNAVAILABLE: 'unavailable',
    DENIED: 'denied',
    LIMITED: 'limited',
    GRANTED: 'granted',
    BLOCKED: 'blocked',
  },
}));
